name: Draw ZMK keymaps
on: [push, pull_request, workflow_dispatch]

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "draw-keymaps.yml"
      output_folder: "docs/images"
      amend_commit: false
